### ISSUE TITLE
FAQ references "files.gpg" instead of "encrypt".

### ISSUE THREAD

**Issue by ericvsmith** [yadm-dev/yadm#334]
It looks like this didn't get updated when the file name changed.

PR to follow.

**Comment by rasa** [comment]
@ericvsmith You are right that the file `files.gpg` was obsolete. Unfortunately, it was renamed to `~/.local/share/yadm/archive`, not `~/.config/yadm/encrypt`. That file is still used and contains the names of the files to be encrypted. I created #336 to fix. I hope this is OK, as I don't want to step on your toes. If Tim rejects my PR and asks you to update yours, I will not take offense, Thanks for catching this!

**Comment by ericvsmith** [comment]
I can't believe I screwed that up! Thanks for catching it. I'll close #335 in deference to #336.

**Comment by rasa** [comment]
No, thank YOU for catching the glitch! And thanks for not taking offense. I should have just commented on #334 and let you fix/close the PR as you saw fit.

**Comment by ericvsmith** [comment]
We're all just trying to make yadm better. It's not possible to take offense on such constructive (and correct) criticism. I'd forgotten to sign #334, so now you've saved me the hassle!

**Comment by rasa** [comment]
@ericvsmith Yeah, but at least you branched off dev-pages! I screwed up #336 by branching off of gh-pages. Fixed in #337.

**Comment by erijo** [comment]
The fix for this has been merged.
