### ISSUE TITLE
Support "!=" in built-in template processor

### ISSUE THREAD

**Issue by xenoterracide** [yadm-dev/yadm#358]
maybe a bug, maybe a PEBCAK (I apologize if it is), I have this code, but for some reason the output of `yadm alt` doesn't include the contents of the `developer.sh`
```
{% if yadm.user != "root" %}
  {% include "../extra/developer.sh" %}
{% endif %}
```
https://github.com/xenoterracide/dotfiles/blob/2002b498c5bfad7c93b959dcbbf7e75fdb69d4a2/.config/yadm/alt/.zshrc%23%23template%2Ce.zsh#L34

**Comment by erijo** [comment]
Does it work if you instead use == and put the include in an else clause?

**Comment by xenoterracide** [comment]
yes and no, this doesn't, it treats the include as just text, but if I remove the indentation it works. changing that may be another ticket... though the way I'd like it to behave is include that code prepended with that indentation. I don't think I should need the else for this though.
```
{% if yadm.user == "root" %}
{% else %}
  {% include "../extra/developer.zsh" %}
{% endif %}
```

**Comment by erijo** [comment]
Yes, {% must be first on the line and only == is supported. For more advanced templates you could perhaps use ninja instead?

**Comment by xenoterracide** [comment]
maybe, but only having `==` is unintuitive. If that's all that *can* be supported perhaps it's possible to throw an error? I honestly haven't considered my config to be particularly complicated, honestly this is the only conditional I have.
