### ISSUE TITLE
yadmignore

### ISSUE THREAD

**Issue by xenoterracide** [yadm-dev/yadm#508]
### Is your feature request related to a problem? Please describe.

I don't care for yadm sharing a configuration with `gitignore` this has caused some heartburn for me in software development because a global gitignore is also used for all of my repo's, and there are patterns both directions I'd rather not apply, and those that I'd like to share. Related (but not the only issue) #355 

### Describe the solution you'd like

I would like to see a `~/.config/yadm/ignore` file introduced, so I can keep them separate. Also possibly a `~/.yadmignore` although I'm less enthusiastic about that, but I speculate it'd be easier to template that one, so that my ignores can share code, but not be the same.

I think this feature should also include a configuration option to disable respecting gitignore.

note: a global gitignore can also live at `~/.config/git/ignore` now.

### Other options

I don't consider the documented exclude file a great option because the global git ignore is still respected, and I'd speculate this particular file based on it's location either isn't yadm trackable or that's probably not a great idea to store it in yadm, you probably could, but probably not a great idea.

### Additional context

```
bash version 5.2.37(1)-release
 git version 2.46.1
yadm version 3.2.2
```

**Comment by erijo** [comment]
Have you considered setting `core.excludesFile` in `~/.gitconfig` using includeIf? Something like the following (untested):
```
# In ~/.gitconfig
[includeIf "gitdir:~/.local/share/yadm/repo.git"]
  path = .gitconfig.yadm

# In ~/.gitconfig.yadm
[core]
  excludesFile = ~/.config/yadm/ignore
```

**Comment by xenoterracide** [comment]
I didn't know there was such a thing as `includeIf`, learning about all the new features of git lately.

**Comment by erijo** [comment]
I'm closing this issue for now. Feel free to reopen it if needed.
